"""empty message

Revision ID: 24ecc643eb2e
Revises: 
Create Date: 2022-05-17 19:20:09.666918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ecc643eb2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('item_code', sa.String(length=120), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=True),
    sa.Column('item_unit_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('calling_name', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('nic', sa.String(length=12), nullable=True),
    sa.Column('emergency_contact', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_no', sa.String(length=20), nullable=True),
    sa.Column('contact_no', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nic')
    )
    op.create_table('production_team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('production_team_name', sa.String(length=200), nullable=True),
    sa.Column('production_team_email', sa.String(length=120), nullable=True),
    sa.Column('production_team_contact_no', sa.String(length=20), nullable=True),
    sa.Column('production_team_address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_team_email')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('supplier_email', sa.String(length=120), nullable=True),
    sa.Column('supplier_contact_no', sa.String(length=20), nullable=True),
    sa.Column('supplier_address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('calling_name', sa.String(length=50), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_logout', sa.DateTime(), nullable=True),
    sa.Column('nic', sa.String(length=12), nullable=True),
    sa.Column('contact_no', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('user_group', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nic')
    )
    op.create_table('gin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gin_name', sa.String(length=200), nullable=True),
    sa.Column('gin_created_date', sa.Date(), nullable=True),
    sa.Column('gin_expected_date', sa.Date(), nullable=True),
    sa.Column('production_team_id', sa.Integer(), nullable=True),
    sa.Column('gin_state', sa.String(length=120), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['production_team_id'], ['production_team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grn',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grn_name', sa.String(length=200), nullable=True),
    sa.Column('grn_created_date', sa.Date(), nullable=True),
    sa.Column('grn_expected_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('grn_state', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('production_order_name', sa.String(length=200), nullable=True),
    sa.Column('production_order_created_date', sa.Date(), nullable=True),
    sa.Column('production_order_expected_date', sa.Date(), nullable=True),
    sa.Column('production_team_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('production_order_state', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['production_team_id'], ['production_team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_name', sa.String(length=200), nullable=True),
    sa.Column('purchase_order_created_date', sa.Date(), nullable=True),
    sa.Column('purchase_order_expected_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_state', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gin_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name_line', sa.String(length=10), nullable=True),
    sa.Column('item_quantity_line', sa.Integer(), nullable=True),
    sa.Column('item_sent_quantity_line', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('production_team_id', sa.Integer(), nullable=True),
    sa.Column('gin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gin_id'], ['gin.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['production_team_id'], ['production_team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grn_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name_line', sa.String(length=10), nullable=True),
    sa.Column('item_quantity_line', sa.Integer(), nullable=True),
    sa.Column('item_received_quantity_line', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('grn_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grn_id'], ['grn.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_order_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name_line', sa.String(length=10), nullable=True),
    sa.Column('item_quantity_line', sa.Integer(), nullable=True),
    sa.Column('item_sent_quantity_line', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('production_team_id', sa.Integer(), nullable=True),
    sa.Column('production_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_order.id'], ),
    sa.ForeignKeyConstraint(['production_team_id'], ['production_team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name_line', sa.String(length=10), nullable=True),
    sa.Column('item_quantity_line', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_order_line')
    op.drop_table('production_order_line')
    op.drop_table('grn_line')
    op.drop_table('gin_line')
    op.drop_table('purchase_order')
    op.drop_table('production_order')
    op.drop_table('grn')
    op.drop_table('gin')
    op.drop_table('user')
    op.drop_table('supplier')
    op.drop_table('sample')
    op.drop_table('production_team')
    op.drop_table('member')
    op.drop_table('items')
    # ### end Alembic commands ###
