"""empty message

Revision ID: 40cc92fe7e7b
Revises: 24ecc643eb2e
Create Date: 2022-05-17 19:42:19.978513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40cc92fe7e7b'
down_revision = '24ecc643eb2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_line', sa.Column('item_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_line', 'item_price')
    # ### end Alembic commands ###
