"""empty message

Revision ID: 765f931db276
Revises: 40cc92fe7e7b
Create Date: 2022-05-21 13:47:22.669891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765f931db276'
down_revision = '40cc92fe7e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('purchase_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order', 'purchase_total')
    # ### end Alembic commands ###
