"""empty message

Revision ID: a475c3bdf783
Revises: 765f931db276
Create Date: 2022-05-21 13:55:45.027269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a475c3bdf783'
down_revision = '765f931db276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_line', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('purchase_order_line', sa.Column('unit_price', sa.Integer(), nullable=True))
    op.add_column('purchase_order_line', sa.Column('subtotal', sa.Integer(), nullable=True))
    op.drop_column('purchase_order_line', 'description')
    op.drop_column('purchase_order_line', 'item_price')
    op.drop_column('purchase_order_line', 'item_name_line')
    op.drop_column('purchase_order_line', 'item_quantity_line')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_line', sa.Column('item_quantity_line', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchase_order_line', sa.Column('item_name_line', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('purchase_order_line', sa.Column('item_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchase_order_line', sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('purchase_order_line', 'subtotal')
    op.drop_column('purchase_order_line', 'unit_price')
    op.drop_column('purchase_order_line', 'quantity')
    # ### end Alembic commands ###
